<?php

namespace Field\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findAllActiveUsers()
    {
        $qb = $this->createQueryBuilder('user');
        $q = $qb->select('user')
            ->where('user.enabled = true')
            ->andWhere('user.name != :name')
            ->setParameter('name', 'anonymous')
            ->getQuery();

        return $q->getResult();
    }
}
