# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:

services:
    user.registration.completed:
            class: AppBundle\EventListener\RegistrationListener
            arguments:
                - "@mailer"
                - "@router"
                - "@templating"
                - "%contact_email%"
                - "%contact_email_name%"
                - "%secret%"
            tags:
                - { name: kernel.event_listener, event: user.registration.completed, method: onRegistrationCompleted }
    user.resetting.password:
            class: AppBundle\EventListener\ResetPasswordListener
            arguments:
                - "@mailer"
                - "@router"
                - "@templating"
                - "%contact_email%"
                - "%contact_email_name%"
                - "%secret%"
            tags:
                - { name: kernel.event_listener, event: user.resetting.password, method: onResettingPassword }