# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:

services:
    user.registration.completed:
            class: UserBundle\EventListener\RegistrationListener
            arguments:
                - "@mailer"
                - "@router"
                - "@templating"
                - "%contact_email%"
                - "%contact_email_name%"
                - "%secret%"
            tags:
                - { name: kernel.event_listener, event: user.registration.completed, method: onRegistrationCompleted }

    user.updated:
            class: UserBundle\EventListener\UserUpdatedListener
            arguments:
                - "@doctrine.orm.entity_manager"
            tags:
                - { name: kernel.event_listener, event: user.updated, method: onUserUpdated }

    user.login:
            class: UserBundle\EventListener\UserLoginListener
            arguments:
                - "@doctrine.orm.entity_manager"
            tags:
                - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

    user.resetting.password:
            class: UserBundle\EventListener\ResetPasswordListener
            arguments:
                - "@mailer"
                - "@router"
                - "@templating"
                - "%contact_email%"
                - "%contact_email_name%"
                - "%secret%"
            tags:
                - { name: kernel.event_listener, event: user.resetting.password, method: onResettingPassword }

    admin.resetting.password:
                class: UserBundle\EventListener\Admin\ResetPasswordListener
                arguments:
                    - "@mailer"
                    - "@router"
                    - "@templating"
                    - "%contact_email%"
                    - "%contact_email_name%"
                tags:
                    - { name: kernel.event_listener, event: admin.resetting.password, method: onResettingPassword }